export const ENV_CONFIG = {
  DB: {
    HOST: 'DB_HOST',
    PORT: 'DB_PORT',
    USER: 'DB_USER',
    PASSWORD: 'DB_PASSWORD',
    DATABASE: 'DB_DATABASE',
  },
  AWS: {
    STATE: 'AWS_STATE',
    REGION: 'AWS_REGION',
    ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID',
    SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY',
    SQS_NAME: 'SQS_NAME',
    SQS_QUEUE_URL: 'SQS_QUEUE_URL',
    SQS_ENDPOINT: 'SQS_ENDPOINT',
  },
};
